<section class="container">
    <div class="row">
        <div class="column-12 text-center m-top-10">
            <h4><?php echo $_welcome; ?></h4>
            <p><?php echo $_translate->__('Welcome! This is the littleMVC.');?></p>
            <p><?php echo $_translate->__('See another page:');?> <a href="<?php echo URL; ?>page/edit/<?php echo rand(); ?>"><?php echo $_translate->__('Exemple page with URL parameter');?></a>.</p>
        </div>
    </div>
</section>