<section class="container">
    <div class="row">
        <div class="column-12 text-center m-top-10">
            <h3><?php echo $_translate->__('Error 404!');?> </h3>
            <h5><?php echo $_translate->__('Page not found...');?> </h5>
            <p class="m-top-1"><?php echo $_translate->__('You wanna');?> <a href="<?php echo URL; ?>"><?php echo $_translate->__('go home');?></a>?</p>
        </div>
    </div>
</section>