<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title><?php echo $title; ?></title>
        <link rel="stylesheet" type="text/css" href="<?php echo URL; ?>assets/css/main.css">
    </head>
    <body>
        <div id="wrapper">
            <?php echo $content; ?>
        </div>
    </body>
</html>
