<?php
/*
 * Get url param id
 */
$_id = rand();
?>
<section class="container">
    <div class="row">
        <div class="column-12 text-center m-top-10">
            <p><?php echo $_translate->__("This page have a hyphen in URL, but the function have a default structure <b>anotherPage</b>.");?></p>
            <p><?php echo $_translate->__('In the next page you can see the url parameter. See');?> <a href="<?php echo URL; ?>page/another-page/<?php echo $_id; ?>"><?php echo $_id; ?></a>.</p>
            <p class="m-top-1"><?php echo $_translate->__("You wanna");?> <a href="<?php echo URL; ?>"><?php echo $_translate->__("go back");?></a>?</p>
        </div>
    </div>
</section>