<?php
/*
 * Get url param id
 */
$_id = $_model->getParam();
?>
<section class="container">
    <div class="row">
        <div class="column-12 text-center m-top-10">
            <p><?php echo $_translate->__("You see this page? Nice! It's works.");?></p>
            <p><?php echo $_translate->__("This page took the parameter");?> <a href="<?php echo URL; ?>page/edit/<?php echo $_id; ?>"><?php echo $_id; ?></a>.</p>
            <p class="m-top-1"><?php echo $_translate->__("You wanna");?> <a href="<?php echo URL; ?>page"><?php echo $_translate->__("go back");?></a>?</p>
        </div>
    </div>
</section>